### ISSUE TITLE
Sdk sources

### ISSUE THREAD

**Issue by jorichard** [mdudel/CoTreceiver#1]
Hello,

could you make the CoT sdk sources available on github as well? Maybe another project to hold the sdk?

Thanks

**Comment by mdudel** [comment]
Hi,
The only copy of the CoT SDK I could find is the SDK-Java-1.0.1.zip which is present. the zip seemed corrupt and essentially contains some JavaDocs and and the CursorOnTarget-1.0.1.jar . That jar is in the lib folder. That is all I have.

**Comment by bradh** [comment]
Is the SDK Distro A?

**Comment by mdudel** [comment]
What do you mean by "Distro A"? The SDK is version 1.0.1 23APR2013. The term "SDK" is a bit overblown since the developer still has to do the heavy lifting of parsing the CoT XML.

**Comment by mdudel** [comment]
> could you make the CoT sdk sources available on github as well? Maybe another project to hold the sdk?

If you are seeking to extract information from the CoT messages then perhaps look at the method dumpCoTevent in the CoTParser class.

**Comment by bradh** [comment]
I wondered if there was a "Distribution Statement" - A is public release. I'm trying to work out how much of CoT is "legal" to redistribute. Clearly some of it is, but I expect some of it won't be.

**Comment by mdudel** [comment]
See the xsds for the embedded distribution statements (lib/xsd folder). The SDK (which really is not an SDK but a set of utility classes) is based upon those core schemas.  The core CoT that this project is based upon is "Approved for Public Release; Distribution Unlimited".  Custom schema extensions and bindings are beyond the scope of this project.
